#!usr/bin/env python

"""Prints the unique gene names from a t_data.ctab file. """

##after each loop, take out next name and compare. if not, add 1
## we have n lines, n^2 time to parse work. search through all gene names for each file. 


import sys

#list of genes
#gene_names_seen=[]; lists, dictionaries can be found very quickly because of hashtables. doesnt have to scan all the keys. it can just hash them. 
gene_names_seen={}

for i, line in enumerate( sys.stdin):
if i==0:
continue


fields = line.rstrip("\r\n").split("\t")
gene_name = fields[9]


if gene_names_seen not in gene_names_seen:
	gene_names_seen.append(gene_name)

for gene_name in gene_names_seen:
	print gene_name

# 3rd way
#gene_names_seen{gene_name} = True , dict

#gene_names_see.add(gene_name), add

#count number of individual gene names


gene_names_seen{gene_name} = True , dict



