#!/usr/bin/env python
# Usage: 

# Average "SIGNAL" over each promoter
# output from 2, & bigWig, 
# bigWig computes avg score of a bigWig over each bed. 
# take this avg score 

import sys
import pandas as pd
import numpy as np

#input: <.py> <bw> <bed> <out.tab name>
bw = sys.argv(1)
bed = sys.argv(2)




bigWigAverageOverBed bw bed p3_out.tab